// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dues.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "indicer/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DuesServiceName is the fully-qualified name of the DuesService service.
	DuesServiceName = "dues.DuesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DuesServiceAppendIfExistsProcedure is the fully-qualified name of the DuesService's
	// AppendIfExists RPC.
	DuesServiceAppendIfExistsProcedure = "/dues.DuesService/AppendIfExists"
	// DuesServiceStreamFileProcedure is the fully-qualified name of the DuesService's StreamFile RPC.
	DuesServiceStreamFileProcedure = "/dues.DuesService/StreamFile"
	// DuesServiceGetEviFilesProcedure is the fully-qualified name of the DuesService's GetEviFiles RPC.
	DuesServiceGetEviFilesProcedure = "/dues.DuesService/GetEviFiles"
	// DuesServiceGetPartiFilesProcedure is the fully-qualified name of the DuesService's GetPartiFiles
	// RPC.
	DuesServiceGetPartiFilesProcedure = "/dues.DuesService/GetPartiFiles"
	// DuesServiceGetIdxFilesProcedure is the fully-qualified name of the DuesService's GetIdxFiles RPC.
	DuesServiceGetIdxFilesProcedure = "/dues.DuesService/GetIdxFiles"
	// DuesServiceSearchProcedure is the fully-qualified name of the DuesService's Search RPC.
	DuesServiceSearchProcedure = "/dues.DuesService/Search"
)

// DuesServiceClient is a client for the dues.DuesService service.
type DuesServiceClient interface {
	AppendIfExists(context.Context, *connect.Request[pb.AppendIfExistsReq]) (*connect.Response[pb.AppendIfExistsRes], error)
	StreamFile(context.Context) *connect.ClientStreamForClient[pb.StreamFileReq, pb.StreamFileRes]
	GetEviFiles(context.Context, *connect.Request[pb.GetEviFilesReq]) (*connect.Response[pb.GetEviFilesRes], error)
	GetPartiFiles(context.Context, *connect.Request[pb.GetPartiFilesReq]) (*connect.Response[pb.GetPartiFilesRes], error)
	GetIdxFiles(context.Context, *connect.Request[pb.GetIdxFilesReq]) (*connect.Response[pb.GetIdxFilesRes], error)
	Search(context.Context, *connect.Request[pb.SearchReq]) (*connect.Response[pb.SearchRes], error)
}

// NewDuesServiceClient constructs a client for the dues.DuesService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDuesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DuesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	duesServiceMethods := pb.File_dues_proto.Services().ByName("DuesService").Methods()
	return &duesServiceClient{
		appendIfExists: connect.NewClient[pb.AppendIfExistsReq, pb.AppendIfExistsRes](
			httpClient,
			baseURL+DuesServiceAppendIfExistsProcedure,
			connect.WithSchema(duesServiceMethods.ByName("AppendIfExists")),
			connect.WithClientOptions(opts...),
		),
		streamFile: connect.NewClient[pb.StreamFileReq, pb.StreamFileRes](
			httpClient,
			baseURL+DuesServiceStreamFileProcedure,
			connect.WithSchema(duesServiceMethods.ByName("StreamFile")),
			connect.WithClientOptions(opts...),
		),
		getEviFiles: connect.NewClient[pb.GetEviFilesReq, pb.GetEviFilesRes](
			httpClient,
			baseURL+DuesServiceGetEviFilesProcedure,
			connect.WithSchema(duesServiceMethods.ByName("GetEviFiles")),
			connect.WithClientOptions(opts...),
		),
		getPartiFiles: connect.NewClient[pb.GetPartiFilesReq, pb.GetPartiFilesRes](
			httpClient,
			baseURL+DuesServiceGetPartiFilesProcedure,
			connect.WithSchema(duesServiceMethods.ByName("GetPartiFiles")),
			connect.WithClientOptions(opts...),
		),
		getIdxFiles: connect.NewClient[pb.GetIdxFilesReq, pb.GetIdxFilesRes](
			httpClient,
			baseURL+DuesServiceGetIdxFilesProcedure,
			connect.WithSchema(duesServiceMethods.ByName("GetIdxFiles")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[pb.SearchReq, pb.SearchRes](
			httpClient,
			baseURL+DuesServiceSearchProcedure,
			connect.WithSchema(duesServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
	}
}

// duesServiceClient implements DuesServiceClient.
type duesServiceClient struct {
	appendIfExists *connect.Client[pb.AppendIfExistsReq, pb.AppendIfExistsRes]
	streamFile     *connect.Client[pb.StreamFileReq, pb.StreamFileRes]
	getEviFiles    *connect.Client[pb.GetEviFilesReq, pb.GetEviFilesRes]
	getPartiFiles  *connect.Client[pb.GetPartiFilesReq, pb.GetPartiFilesRes]
	getIdxFiles    *connect.Client[pb.GetIdxFilesReq, pb.GetIdxFilesRes]
	search         *connect.Client[pb.SearchReq, pb.SearchRes]
}

// AppendIfExists calls dues.DuesService.AppendIfExists.
func (c *duesServiceClient) AppendIfExists(ctx context.Context, req *connect.Request[pb.AppendIfExistsReq]) (*connect.Response[pb.AppendIfExistsRes], error) {
	return c.appendIfExists.CallUnary(ctx, req)
}

// StreamFile calls dues.DuesService.StreamFile.
func (c *duesServiceClient) StreamFile(ctx context.Context) *connect.ClientStreamForClient[pb.StreamFileReq, pb.StreamFileRes] {
	return c.streamFile.CallClientStream(ctx)
}

// GetEviFiles calls dues.DuesService.GetEviFiles.
func (c *duesServiceClient) GetEviFiles(ctx context.Context, req *connect.Request[pb.GetEviFilesReq]) (*connect.Response[pb.GetEviFilesRes], error) {
	return c.getEviFiles.CallUnary(ctx, req)
}

// GetPartiFiles calls dues.DuesService.GetPartiFiles.
func (c *duesServiceClient) GetPartiFiles(ctx context.Context, req *connect.Request[pb.GetPartiFilesReq]) (*connect.Response[pb.GetPartiFilesRes], error) {
	return c.getPartiFiles.CallUnary(ctx, req)
}

// GetIdxFiles calls dues.DuesService.GetIdxFiles.
func (c *duesServiceClient) GetIdxFiles(ctx context.Context, req *connect.Request[pb.GetIdxFilesReq]) (*connect.Response[pb.GetIdxFilesRes], error) {
	return c.getIdxFiles.CallUnary(ctx, req)
}

// Search calls dues.DuesService.Search.
func (c *duesServiceClient) Search(ctx context.Context, req *connect.Request[pb.SearchReq]) (*connect.Response[pb.SearchRes], error) {
	return c.search.CallUnary(ctx, req)
}

// DuesServiceHandler is an implementation of the dues.DuesService service.
type DuesServiceHandler interface {
	AppendIfExists(context.Context, *connect.Request[pb.AppendIfExistsReq]) (*connect.Response[pb.AppendIfExistsRes], error)
	StreamFile(context.Context, *connect.ClientStream[pb.StreamFileReq]) (*connect.Response[pb.StreamFileRes], error)
	GetEviFiles(context.Context, *connect.Request[pb.GetEviFilesReq]) (*connect.Response[pb.GetEviFilesRes], error)
	GetPartiFiles(context.Context, *connect.Request[pb.GetPartiFilesReq]) (*connect.Response[pb.GetPartiFilesRes], error)
	GetIdxFiles(context.Context, *connect.Request[pb.GetIdxFilesReq]) (*connect.Response[pb.GetIdxFilesRes], error)
	Search(context.Context, *connect.Request[pb.SearchReq]) (*connect.Response[pb.SearchRes], error)
}

// NewDuesServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDuesServiceHandler(svc DuesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	duesServiceMethods := pb.File_dues_proto.Services().ByName("DuesService").Methods()
	duesServiceAppendIfExistsHandler := connect.NewUnaryHandler(
		DuesServiceAppendIfExistsProcedure,
		svc.AppendIfExists,
		connect.WithSchema(duesServiceMethods.ByName("AppendIfExists")),
		connect.WithHandlerOptions(opts...),
	)
	duesServiceStreamFileHandler := connect.NewClientStreamHandler(
		DuesServiceStreamFileProcedure,
		svc.StreamFile,
		connect.WithSchema(duesServiceMethods.ByName("StreamFile")),
		connect.WithHandlerOptions(opts...),
	)
	duesServiceGetEviFilesHandler := connect.NewUnaryHandler(
		DuesServiceGetEviFilesProcedure,
		svc.GetEviFiles,
		connect.WithSchema(duesServiceMethods.ByName("GetEviFiles")),
		connect.WithHandlerOptions(opts...),
	)
	duesServiceGetPartiFilesHandler := connect.NewUnaryHandler(
		DuesServiceGetPartiFilesProcedure,
		svc.GetPartiFiles,
		connect.WithSchema(duesServiceMethods.ByName("GetPartiFiles")),
		connect.WithHandlerOptions(opts...),
	)
	duesServiceGetIdxFilesHandler := connect.NewUnaryHandler(
		DuesServiceGetIdxFilesProcedure,
		svc.GetIdxFiles,
		connect.WithSchema(duesServiceMethods.ByName("GetIdxFiles")),
		connect.WithHandlerOptions(opts...),
	)
	duesServiceSearchHandler := connect.NewUnaryHandler(
		DuesServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(duesServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dues.DuesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DuesServiceAppendIfExistsProcedure:
			duesServiceAppendIfExistsHandler.ServeHTTP(w, r)
		case DuesServiceStreamFileProcedure:
			duesServiceStreamFileHandler.ServeHTTP(w, r)
		case DuesServiceGetEviFilesProcedure:
			duesServiceGetEviFilesHandler.ServeHTTP(w, r)
		case DuesServiceGetPartiFilesProcedure:
			duesServiceGetPartiFilesHandler.ServeHTTP(w, r)
		case DuesServiceGetIdxFilesProcedure:
			duesServiceGetIdxFilesHandler.ServeHTTP(w, r)
		case DuesServiceSearchProcedure:
			duesServiceSearchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDuesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDuesServiceHandler struct{}

func (UnimplementedDuesServiceHandler) AppendIfExists(context.Context, *connect.Request[pb.AppendIfExistsReq]) (*connect.Response[pb.AppendIfExistsRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dues.DuesService.AppendIfExists is not implemented"))
}

func (UnimplementedDuesServiceHandler) StreamFile(context.Context, *connect.ClientStream[pb.StreamFileReq]) (*connect.Response[pb.StreamFileRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dues.DuesService.StreamFile is not implemented"))
}

func (UnimplementedDuesServiceHandler) GetEviFiles(context.Context, *connect.Request[pb.GetEviFilesReq]) (*connect.Response[pb.GetEviFilesRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dues.DuesService.GetEviFiles is not implemented"))
}

func (UnimplementedDuesServiceHandler) GetPartiFiles(context.Context, *connect.Request[pb.GetPartiFilesReq]) (*connect.Response[pb.GetPartiFilesRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dues.DuesService.GetPartiFiles is not implemented"))
}

func (UnimplementedDuesServiceHandler) GetIdxFiles(context.Context, *connect.Request[pb.GetIdxFilesReq]) (*connect.Response[pb.GetIdxFilesRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dues.DuesService.GetIdxFiles is not implemented"))
}

func (UnimplementedDuesServiceHandler) Search(context.Context, *connect.Request[pb.SearchReq]) (*connect.Response[pb.SearchRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dues.DuesService.Search is not implemented"))
}
