// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: dues.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DuesService_AppendIfExists_FullMethodName    = "/dues.DuesService/AppendIfExists"
	DuesService_StreamFile_FullMethodName        = "/dues.DuesService/StreamFile"
	DuesService_GetEviFiles_FullMethodName       = "/dues.DuesService/GetEviFiles"
	DuesService_GetPartitionFiles_FullMethodName = "/dues.DuesService/GetPartitionFiles"
	DuesService_GetIndexedFiles_FullMethodName   = "/dues.DuesService/GetIndexedFiles"
	DuesService_Search_FullMethodName            = "/dues.DuesService/Search"
)

// DuesServiceClient is the client API for DuesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DuesServiceClient interface {
	AppendIfExists(ctx context.Context, in *AppendIfExistsReq, opts ...grpc.CallOption) (*AppendIfExistsRes, error)
	StreamFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamFileReq, StreamFileRes], error)
	GetEviFiles(ctx context.Context, in *GetEviFilesReq, opts ...grpc.CallOption) (*GetEviFilesRes, error)
	GetPartitionFiles(ctx context.Context, in *GetPartitionFilesReq, opts ...grpc.CallOption) (*GetPartitionFilesRes, error)
	GetIndexedFiles(ctx context.Context, in *GetIndexedFilesReq, opts ...grpc.CallOption) (*GetIndexedFilesRes, error)
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchRes, error)
}

type duesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDuesServiceClient(cc grpc.ClientConnInterface) DuesServiceClient {
	return &duesServiceClient{cc}
}

func (c *duesServiceClient) AppendIfExists(ctx context.Context, in *AppendIfExistsReq, opts ...grpc.CallOption) (*AppendIfExistsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendIfExistsRes)
	err := c.cc.Invoke(ctx, DuesService_AppendIfExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duesServiceClient) StreamFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamFileReq, StreamFileRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DuesService_ServiceDesc.Streams[0], DuesService_StreamFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFileReq, StreamFileRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuesService_StreamFileClient = grpc.ClientStreamingClient[StreamFileReq, StreamFileRes]

func (c *duesServiceClient) GetEviFiles(ctx context.Context, in *GetEviFilesReq, opts ...grpc.CallOption) (*GetEviFilesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEviFilesRes)
	err := c.cc.Invoke(ctx, DuesService_GetEviFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duesServiceClient) GetPartitionFiles(ctx context.Context, in *GetPartitionFilesReq, opts ...grpc.CallOption) (*GetPartitionFilesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartitionFilesRes)
	err := c.cc.Invoke(ctx, DuesService_GetPartitionFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duesServiceClient) GetIndexedFiles(ctx context.Context, in *GetIndexedFilesReq, opts ...grpc.CallOption) (*GetIndexedFilesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexedFilesRes)
	err := c.cc.Invoke(ctx, DuesService_GetIndexedFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duesServiceClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRes)
	err := c.cc.Invoke(ctx, DuesService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DuesServiceServer is the server API for DuesService service.
// All implementations must embed UnimplementedDuesServiceServer
// for forward compatibility.
type DuesServiceServer interface {
	AppendIfExists(context.Context, *AppendIfExistsReq) (*AppendIfExistsRes, error)
	StreamFile(grpc.ClientStreamingServer[StreamFileReq, StreamFileRes]) error
	GetEviFiles(context.Context, *GetEviFilesReq) (*GetEviFilesRes, error)
	GetPartitionFiles(context.Context, *GetPartitionFilesReq) (*GetPartitionFilesRes, error)
	GetIndexedFiles(context.Context, *GetIndexedFilesReq) (*GetIndexedFilesRes, error)
	Search(context.Context, *SearchReq) (*SearchRes, error)
	mustEmbedUnimplementedDuesServiceServer()
}

// UnimplementedDuesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDuesServiceServer struct{}

func (UnimplementedDuesServiceServer) AppendIfExists(context.Context, *AppendIfExistsReq) (*AppendIfExistsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendIfExists not implemented")
}
func (UnimplementedDuesServiceServer) StreamFile(grpc.ClientStreamingServer[StreamFileReq, StreamFileRes]) error {
	return status.Errorf(codes.Unimplemented, "method StreamFile not implemented")
}
func (UnimplementedDuesServiceServer) GetEviFiles(context.Context, *GetEviFilesReq) (*GetEviFilesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEviFiles not implemented")
}
func (UnimplementedDuesServiceServer) GetPartitionFiles(context.Context, *GetPartitionFilesReq) (*GetPartitionFilesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartitionFiles not implemented")
}
func (UnimplementedDuesServiceServer) GetIndexedFiles(context.Context, *GetIndexedFilesReq) (*GetIndexedFilesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndexedFiles not implemented")
}
func (UnimplementedDuesServiceServer) Search(context.Context, *SearchReq) (*SearchRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDuesServiceServer) mustEmbedUnimplementedDuesServiceServer() {}
func (UnimplementedDuesServiceServer) testEmbeddedByValue()                     {}

// UnsafeDuesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DuesServiceServer will
// result in compilation errors.
type UnsafeDuesServiceServer interface {
	mustEmbedUnimplementedDuesServiceServer()
}

func RegisterDuesServiceServer(s grpc.ServiceRegistrar, srv DuesServiceServer) {
	// If the following call pancis, it indicates UnimplementedDuesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DuesService_ServiceDesc, srv)
}

func _DuesService_AppendIfExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendIfExistsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuesServiceServer).AppendIfExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuesService_AppendIfExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuesServiceServer).AppendIfExists(ctx, req.(*AppendIfExistsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuesService_StreamFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DuesServiceServer).StreamFile(&grpc.GenericServerStream[StreamFileReq, StreamFileRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuesService_StreamFileServer = grpc.ClientStreamingServer[StreamFileReq, StreamFileRes]

func _DuesService_GetEviFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEviFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuesServiceServer).GetEviFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuesService_GetEviFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuesServiceServer).GetEviFiles(ctx, req.(*GetEviFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuesService_GetPartitionFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuesServiceServer).GetPartitionFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuesService_GetPartitionFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuesServiceServer).GetPartitionFiles(ctx, req.(*GetPartitionFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuesService_GetIndexedFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexedFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuesServiceServer).GetIndexedFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuesService_GetIndexedFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuesServiceServer).GetIndexedFiles(ctx, req.(*GetIndexedFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuesService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuesServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuesService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuesServiceServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DuesService_ServiceDesc is the grpc.ServiceDesc for DuesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DuesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dues.DuesService",
	HandlerType: (*DuesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendIfExists",
			Handler:    _DuesService_AppendIfExists_Handler,
		},
		{
			MethodName: "GetEviFiles",
			Handler:    _DuesService_GetEviFiles_Handler,
		},
		{
			MethodName: "GetPartitionFiles",
			Handler:    _DuesService_GetPartitionFiles_Handler,
		},
		{
			MethodName: "GetIndexedFiles",
			Handler:    _DuesService_GetIndexedFiles_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _DuesService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFile",
			Handler:       _DuesService_StreamFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dues.proto",
}
